##############################################################################
# Copyright (c) 2016 HUAWEI TECHNOLOGIES CO.,LTD and others.
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
- name: nova api db sync
  shell: su -s /bin/sh -c "nova-manage api_db sync" nova
  ignore_errors: "True"
  notify:
    - restart nova service

- name: register the cell0 database
  shell: su -s /bin/sh -c "nova-manage cell_v2 map_cell0" nova
  notify:
    - restart nova service

- name: create the cell1 cell
  shell: su -s /bin/sh -c "nova-manage cell_v2 create_cell --name=cell1 --verbose" nova
  notify:
    - restart nova service

- name: nova db sync
  shell: su -s /bin/sh -c "nova-manage db sync" nova
  notify:
    - restart nova service

- meta: flush_handlers
